library(ggplot2)

SensitivityPlot <-function(rank=T,folder, scd_folder){
  #Changed the folder in which is contained the .RData file
  load(paste0(scd_folder,"Lotka-Volterra-analysis.RData"))  
  # Then, we read all the trajectories generated saving them in a list called
  # ListTraces. List that will be rewritten as a data frame in order to use ggplot.
  # ConfigID represents the initial condition associated to each trajectory,
  # which was generated by using the function implemented in the file Functions.R .
  
  listFile<-list.files(scd_folder,
                       pattern = ".trace")
  
  configID<-t(sapply(1:length(listFile),
                     function(x){
                       return(c(x,config[[1]][[x]][[3]]))
                     }) )
  
  id.traces <- as.numeric(gsub("[^[:digit:].]", "",listFile) )
  
  print(id.traces)
  
  if(rank){
    load(paste0(folder,"ranking_Lotka-Volterra-sensitivity.RData"))
  }else{
    rank <- data.frame(measure = 0 , id = id.traces)
  }
  
  prcc_file_path <- paste0(folder, "prcc_Lotka-Volterra-sensitivity.RData")
  
  if(file.exists(prcc_file_path)) {
    load(prcc_file_path) 
  } else {
    prcc <- data.frame(Param = character(), prcc = numeric(), p.value = numeric(), Time = numeric(), Type = character())
  }
  reference <- as.data.frame(read.csv("Input/reference_data.csv",
                                      header = FALSE,
                                      sep = ""))
  
  ListTraces <- lapply(id.traces, function(x) {
    trace.tmp <- read.csv(paste0(scd_folder, "Lotka-Volterra-analysis-", x, ".trace"), sep = "")
    
    trace.tmp <- data.frame(trace.tmp, ID = x, 
                            rank = rank[which(rank[, 2] == paste0("Lotka-Volterra-analysis-", x, ".trace")), 1])
    
    return(trace.tmp)
  })
    rank2 <- lapply(id.traces, function(x) {
    valori <- config[[1]][[x]][[3]]
    predator_value <- valori[1]
    prey_value <- valori[2]
    
    rnk.tmp <- data.frame(ID = x,
                          distance = rank[which(rank[, 2] == paste0("Lotka-Volterra-analysis-", x, ".trace")), 1],
                          prey_rate = prey_value,
                          predator_rate = predator_value)
    return(rnk.tmp)
  })
    
    
  rank2 <- do.call("rbind", rank2)
  traces <- do.call("rbind", ListTraces)
  
  plI <- ggplot(traces, aes(x = Prey, y = Predator, group = ID, color = rank)) +
    geom_path(size = 1) +  
    scale_color_gradientn(colours = c("red", "deepskyblue2", "cyan"),
                          breaks = NULL) +
    theme(axis.text = element_text(size = 18),
          axis.title = element_text(size = 20, face = "bold"),
          legend.text = element_text(size = 18),
          legend.title = element_text(size = 20, face = "bold"),
          legend.position = "right",
          legend.key.size = unit(1.3, "cm"),
          legend.key.width = unit(1.3, "cm")) +
    labs(x = "Prey Population",
         y = "Predator Population",
         color = "Rank") 
  
  prcc_filtered <- prcc[prcc$Param %in% c("init-1", "init-2"), ]
  
  
  
  plPrcc <- ggplot(prcc_filtered, aes(x = Time, y = prcc, colour = Param)) +
    geom_line() + 
    geom_rect(xmin=0, xmax=20, ymin = -0.2, ymax = 0.2, fill = "yellow", alpha = 0.1, inherit.aes = FALSE) +
    labs(x = "Time", y = "PRCC") +
    theme_minimal() +
    scale_colour_manual(values = c("init-1" = "red", "init-2" = "blue"))
  
  #print(plPrcc)
  
}

